// Default content. Seeds localStorage on first visit.
// To publish edits made in /admin.html to everyone, use the dashboard's
// "Export JSON" button and paste the result in here (see README).
var HOP_SEED = {
  categories: [
    { id: 'cat-restaurant', name: 'Restaurant', slug: 'restaurant', order: 0 },
    { id: 'cat-beauty', name: 'Beauty', slug: 'beauty', order: 1 },
    { id: 'cat-healthcare', name: 'Healthcare', slug: 'healthcare', order: 2 },
    { id: 'cat-education', name: 'Education', slug: 'education', order: 3 },
  ],
  subcategories: [
    { id: 'sub-restaurant-reels', categoryId: 'cat-restaurant', name: 'Reels', slug: 'reels', type: 'video', order: 0 },
    { id: 'sub-restaurant-dishes', categoryId: 'cat-restaurant', name: 'Dishes', slug: 'dishes', type: 'photo', order: 1 },
    { id: 'sub-beauty-reels', categoryId: 'cat-beauty', name: 'Reels', slug: 'reels', type: 'video', order: 0 },
    { id: 'sub-beauty-before-after', categoryId: 'cat-beauty', name: 'Before & After', slug: 'before-after', type: 'photo', order: 1 },
    { id: 'sub-healthcare-reels', categoryId: 'cat-healthcare', name: 'Reels', slug: 'reels', type: 'video', order: 0 },
    { id: 'sub-healthcare-facility', categoryId: 'cat-healthcare', name: 'Facility', slug: 'facility', type: 'photo', order: 1 },
    { id: 'sub-education-reels', categoryId: 'cat-education', name: 'Reels', slug: 'reels', type: 'video', order: 0 },
    { id: 'sub-education-campus', categoryId: 'cat-education', name: 'Campus', slug: 'campus', type: 'photo', order: 1 },
  ],
  items: [
    {
      id: 'item-1',
      subcategoryId: 'sub-restaurant-reels',
      title: 'Zafrani Chicken Biryani',
      linkUrl: 'https://www.instagram.com/reel/PLACEHOLDER1/',
      thumbnailUrl: '',
      ratio: 'vertical',
      order: 0,
    },
    {
      id: 'item-2',
      subcategoryId: 'sub-restaurant-reels',
      title: 'Chai aur Lucknow',
      linkUrl: 'https://www.instagram.com/reel/PLACEHOLDER2/',
      thumbnailUrl: '',
      ratio: 'vertical',
      order: 1,
    },
    {
      id: 'item-3',
      subcategoryId: 'sub-restaurant-reels',
      title: 'Ramadan Happiness Meal',
      linkUrl: 'https://www.instagram.com/reel/PLACEHOLDER3/',
      thumbnailUrl: '',
      ratio: 'horizontal',
      order: 2,
    },
    {
      id: 'item-4',
      subcategoryId: 'sub-restaurant-dishes',
      title: 'Table Spread',
      linkUrl: '',
      thumbnailUrl: '',
      ratio: '3:4',
      order: 0,
    },
    {
      id: 'item-5',
      subcategoryId: 'sub-restaurant-dishes',
      title: 'Signature Plate',
      linkUrl: '',
      thumbnailUrl: '',
      ratio: 'square',
      order: 1,
    },
    {
      id: 'item-6',
      subcategoryId: 'sub-beauty-reels',
      title: 'Glow Ritual',
      linkUrl: 'https://www.instagram.com/reel/PLACEHOLDER4/',
      thumbnailUrl: '',
      ratio: 'vertical',
      order: 0,
    },
    {
      id: 'item-7',
      subcategoryId: 'sub-beauty-reels',
      title: 'Bridal Season Prep',
      linkUrl: 'https://www.instagram.com/reel/PLACEHOLDER5/',
      thumbnailUrl: '',
      ratio: 'vertical',
      order: 1,
    },
    {
      id: 'item-8',
      subcategoryId: 'sub-beauty-before-after',
      title: 'Bridal Transformation',
      linkUrl: '',
      thumbnailUrl: '',
      ratio: 'square',
      order: 0,
    },
    {
      id: 'item-9',
      subcategoryId: 'sub-beauty-before-after',
      title: 'Skin Glow Progress',
      linkUrl: '',
      thumbnailUrl: '',
      ratio: '5:4',
      order: 1,
    },
    {
      id: 'item-10',
      subcategoryId: 'sub-healthcare-reels',
      title: 'Zakham pe Marham',
      linkUrl: 'https://www.instagram.com/reel/PLACEHOLDER6/',
      thumbnailUrl: '',
      ratio: 'vertical',
      order: 0,
    },
    {
      id: 'item-11',
      subcategoryId: 'sub-healthcare-reels',
      title: 'Meet the Specialists',
      linkUrl: 'https://www.instagram.com/reel/PLACEHOLDER7/',
      thumbnailUrl: '',
      ratio: 'horizontal',
      order: 1,
    },
    {
      id: 'item-12',
      subcategoryId: 'sub-healthcare-facility',
      title: 'Our Clinic',
      linkUrl: '',
      thumbnailUrl: '',
      ratio: '4:3',
      order: 0,
    },
    {
      id: 'item-13',
      subcategoryId: 'sub-education-reels',
      title: 'Admissions Open 2026',
      linkUrl: 'https://www.instagram.com/reel/PLACEHOLDER8/',
      thumbnailUrl: '',
      ratio: 'vertical',
      order: 0,
    },
    {
      id: 'item-14',
      subcategoryId: 'sub-education-campus',
      title: 'Campus Diaries',
      linkUrl: '',
      thumbnailUrl: '',
      ratio: '4:5',
      order: 0,
    },
    {
      id: 'item-15',
      subcategoryId: 'sub-education-campus',
      title: 'Library Hall',
      linkUrl: '',
      thumbnailUrl: '',
      ratio: '3:4',
      order: 1,
    },
  ],
}
