// Default content. Seeds localStorage on first visit.
// To publish edits made in /admin.html to everyone, use the dashboard's
// "Export JSON" button and paste the result in here (see README).
var HOP_SEED = {
  categories: [
    { id: 'cat-restaurant', name: 'Restaurant', slug: 'restaurant', order: 0 },
    { id: 'cat-beauty', name: 'Beauty', slug: 'beauty', order: 1 },
    { id: 'cat-healthcare', name: 'Healthcare', slug: 'healthcare', order: 2 },
    { id: 'cat-education', name: 'Education', slug: 'education', order: 3 },
  ],
  reels: [
    {
      id: 'reel-1',
      categoryId: 'cat-restaurant',
      title: 'Zafrani Chicken Biryani',
      instagramUrl: 'https://www.instagram.com/reel/PLACEHOLDER1/',
      thumbnailUrl: '',
      orientation: 'vertical',
      order: 0,
    },
    {
      id: 'reel-2',
      categoryId: 'cat-restaurant',
      title: 'Chai aur Lucknow',
      instagramUrl: 'https://www.instagram.com/reel/PLACEHOLDER2/',
      thumbnailUrl: '',
      orientation: 'vertical',
      order: 1,
    },
    {
      id: 'reel-3',
      categoryId: 'cat-restaurant',
      title: 'Ramadan Happiness Meal',
      instagramUrl: 'https://www.instagram.com/reel/PLACEHOLDER3/',
      thumbnailUrl: '',
      orientation: 'horizontal',
      order: 2,
    },
    {
      id: 'reel-4',
      categoryId: 'cat-beauty',
      title: 'Glow Ritual',
      instagramUrl: 'https://www.instagram.com/reel/PLACEHOLDER4/',
      thumbnailUrl: '',
      orientation: 'vertical',
      order: 0,
    },
    {
      id: 'reel-5',
      categoryId: 'cat-beauty',
      title: 'Bridal Season Prep',
      instagramUrl: 'https://www.instagram.com/reel/PLACEHOLDER5/',
      thumbnailUrl: '',
      orientation: 'vertical',
      order: 1,
    },
    {
      id: 'reel-6',
      categoryId: 'cat-healthcare',
      title: 'Zakham pe Marham',
      instagramUrl: 'https://www.instagram.com/reel/PLACEHOLDER6/',
      thumbnailUrl: '',
      orientation: 'vertical',
      order: 0,
    },
    {
      id: 'reel-7',
      categoryId: 'cat-healthcare',
      title: 'Meet the Specialists',
      instagramUrl: 'https://www.instagram.com/reel/PLACEHOLDER7/',
      thumbnailUrl: '',
      orientation: 'horizontal',
      order: 1,
    },
    {
      id: 'reel-8',
      categoryId: 'cat-education',
      title: 'Admissions Open 2026',
      instagramUrl: 'https://www.instagram.com/reel/PLACEHOLDER8/',
      thumbnailUrl: '',
      orientation: 'vertical',
      order: 0,
    },
    {
      id: 'reel-9',
      categoryId: 'cat-education',
      title: 'Campus Diaries',
      instagramUrl: 'https://www.instagram.com/reel/PLACEHOLDER9/',
      thumbnailUrl: '',
      orientation: 'horizontal',
      order: 1,
    },
  ],
}
